version: 2

project_name: jeju

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: jeju
    main: ./cmd/jeju
    binary: jeju
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/cosmtrek/jeju/internal/cli.version={{ .Version }}
      - -X github.com/cosmtrek/jeju/internal/cli.commit={{ .Commit }}
      - -X github.com/cosmtrek/jeju/internal/cli.branch={{ .Branch }}
      - -X github.com/cosmtrek/jeju/internal/cli.date={{ .Date }}

archives:
  - id: jeju
    ids:
      - jeju
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: cosmtrek
    name: jeju
